WIP: Allow multiple inputs in transforms
jvalue/jayvee pull request #347
Opened 2023-05-25 19:49 UTC by georg-schwarz

Closes #335.

Needs some further testing.

2023-06-12 12:15 UTC, felix-oq requested changes
Some suggestions but there is nothing severe among them. I noticed though that the docs are not updated yet.

2023-06-12 12:15 UTC, felix-oq commented on libs/execution/src/lib/transforms/transform-executor.ts
> +    }
Could also be implemented via `ports.map(...)`.

2023-06-12 12:15 UTC, felix-oq commented on libs/execution/src/lib/transforms/transform-executor.ts
> +        const variableValue = column.values[rowIndex]!;
You could use `assert` statements instead of the `!` operator here to improve safety at runtime.

2023-06-12 12:15 UTC, felix-oq commented on libs/execution/src/lib/transforms/transform-executor.ts
> +      }
Consider extracting the loops for setting and deleting values for variables into their own helper functions.

2023-06-12 12:15 UTC, felix-oq commented on libs/extensions/tabular/exec/src/lib/table-transformer-executor.ts
> +            node: context.getProperty('inputColumns')!,
There is `getOrFailProperty` which allows you to omit the `!` operator. Also, you should restrict the diagnostic to the property value, so not the entire property (including its name) is underlined.

Same applies for the other diagnostics.

2023-06-12 12:15 UTC, felix-oq commented on libs/extensions/tabular/lang/src/lib/table-transformer-meta-inf.ts
> +  inputColumn: ['temperatureCelsius'];
```suggestion
  inputColumns: ['temperatureCelsius'];
```

2023-06-16 15:52 UTC, georg-schwarz commented on libs/extensions/tabular/lang/src/lib/table-transformer-meta-inf.ts
> +  }
Should be solved by making the property of type `new CollectionValuetype(PrimitiveValuetypes.Text)` that automatically does validation on text items.

2023-06-23 07:31 UTC, merged