fix: range-constraint and lenght-constraint work with only one bound
jvalue/jayvee pull request #548
Opened 2024-04-15 14:19 UTC by TungstnBallon

It is now possible to only specify one bound when using `lenght-constraint`. However one bound minimum is still required
closes #533

I went ahead and took the liberty to also implement this fix for `range-constraint`.

2024-04-15 14:21 UTC, TungstnBallon commented on libs/execution/src/lib/constraints/executors/length-constraint-executor.ts
> +    return false; // HACK: linter complains about a missing return type otherwise
@rhazn I was unsure what to do if no bound is specified

2024-04-15 14:22 UTC, TungstnBallon commented on libs/execution/src/lib/constraints/executors/range-constraint-executor.ts
> +    assert(upperBound !== undefined || lowerBound !== undefined); // FIXME: throw an actual errror?
see https://github.com/jvalue/jayvee/pull/548/files#r1565882788

2024-04-16 18:07 UTC, TungstnBallon commented on libs/execution/src/lib/constraints/executors/length-constraint-executor.ts
> +    return false; // HACK: linter complains about a missing return type otherwise
As discussed during today's meeting I will handle this by letting all values pass through a constraint without bounds. To compensate this I'm going to add a language server warning.

2024-04-17 10:01 UTC, rhazn requested changes
Thanks for the fix and great that you also expanded it to other constraint types, well done 🥳 . I think the approach taken is not the perfect one though, I left a comment on the `execution-context` towards that.

As always, I could be wrong so if there is a reason why you chose to not go the default value route let me know, otherwise I think it would be better to approach it like that.

2024-04-18 10:31 UTC, rhazn requested changes
I might be missing something but there are no functional changes in this PR, only tests and hints now? Did you merge the functional changes in a different PR?

2024-04-18 10:31 UTC, rhazn commented on libs/execution/test/assets/length-constraint-executor/only-lower-bound.jv
> +		valuetypeAssignmentProperty: "test" oftype ConstraintType;
```suggestion
		valuetypeAssignmentProperty: "test" oftype TestValueType;
```

Not sure how this model even compiles?! 🤔 Same for the other model.

2024-04-28 08:14 UTC, TungstnBallon commented
> I might be missing something but there are no functional changes in this PR, only tests and hints now? Did you merge the functional changes in a different PR?

It seems to work without functional changes. I think this is because all the required properties like `lowerBound` or `lowerBoundInclusive` already have defaults that are used if the property isn't specified in the `.jv` file.
I followed the steps to reproduce from #533 and the error described there is gone too.

2024-05-03 12:47 UTC, rhazn approved these changes
Sounds good, then we have hardened Jayvee for the future with more tests :). For future reference, if you'd like me to review again please always click the re-request review button though.

2024-05-03 13:21 UTC, merged