Cache task "generate"
jvalue/jayvee pull request #580
Opened 2024-05-31 11:55 UTC by joluj

This PR introduces the caching of the task `language-server:generate`.

Current state (before this PR): Langium code is generated on every build of the language-server (and due to library dependencies on every build of the interpreter and other apps). This slows down development.

With changes: `language-server:generate` detects if relevant files are changed and only runs when necessary.

2024-05-31 14:21 UTC, rhazn approved these changes

2024-05-31 14:24 UTC, joluj commented
I'm waiting for @georg-schwarz's feedback as well before merging.

2024-05-31 15:49 UTC, georg-schwarz requested changes
Nice idea!

In an ideal world we'd define all elements in Jayvee itself, but we are not there yet. If you look into the stdlib generator you'll see that some parts of the stdlib are still generated from code, e.g., 

```
'builtin:///stdlib/io-types.jv': Object.values(IOType)
    .map((iotype) => `publish builtin iotype ${iotype};`)
    .join('\n\n'),
```

When changing the IOType enum, the caching should respect that as well. More difficult will be the built-in value types... Probably add the whole directory there.

If you add those things so that caching gets invalidated on their file changes, I'm fine with merging :)

2024-06-17 10:36 UTC, joluj commented
If you change `IOType` or `CSVExtractor.js` (built-in Javee Block), the `language-server` lib is rebuilt / its cache is invalidated. This is how it should be right? So everything works as expected

2024-07-15 08:47 UTC, georg-schwarz approved these changes

2024-07-15 09:00 UTC, merged